CREATE DATABASE owrdb;
CREATE USER dbuser;
ALTER USER dbuser WITH ENCRYPTED PASSWORD 'pa88w0rd';
ALTER DATABASE owrdb OWNER TO dbuser;
\c owrdb;
CREATE TABLE readings(id serial PRIMARY KEY, temperature NUMERIC NULL, pressure NUMERIC NULL, humidity NUMERIC NULL, windspeed NUMERIC NULL, lastupdate TIMESTAMP NOT NULL);
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO dbuser;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO dbuser;
GRANT ALL PRIVILEGES ON DATABASE owrdb TO dbuser;
